""" Generated by Django 4.1.7 on 2023-02-16 06:59 """

from django.db import migrations, models


class Migration(migrations.Migration):
    """Pylint, I hate you"""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventgoer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
                ('is_reseller', models.BooleanField(verbose_name='Reseller')),
            ],
            options={
                'verbose_name': 'Eventgoer',
                'verbose_name_plural': 'Eventgoers',
            },
        ),
    ]
