# Generated by Django 4.1.7 on 2023-03-08 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='tickets',
            field=models.ManyToManyField(related_name='orders', to='ticketing.ticket', verbose_name='Tickets'),
        ),
    ]
