""" Generated by Django 4.1.7 on 2023-02-16 07:02 """

from django.db import migrations, models


class Migration(migrations.Migration):
    """Whyyyy oh why does pylint do this to us?"""

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgoer',
            name='is_reseller',
            field=models.BooleanField(verbose_name='Reseller Account'),
        ),
    ]
