# Generated by Django 4.1.7 on 2023-03-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_order_order_date_alter_order_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ticketing.eventgoer', verbose_name='Purchaser'),
        ),
    ]
