# Generated by Django 4.1.7 on 2023-03-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='order',
            name='holder_name',
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='balance',
            field=models.FloatField(default=5000, verbose_name='User Balance'),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Credit Card Number')),
                ('cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('exp_month', models.CharField(max_length=2, verbose_name='Exipration month')),
                ('exp_year', models.CharField(max_length=4, verbose_name='Exipration year')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Card Holder Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='ticketing.eventgoer', verbose_name='Eventgoer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ticketing.paymentinfo', verbose_name='Payment Info'),
        ),
    ]
