# Generated by Django 4.1.7 on 2023-03-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
        ('ticketing', '0003_alter_order_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='venue_management.concert', verbose_name='Concert'),
        ),
    ]
