# Generated by Django 4.1.7 on 2023-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_eventgoer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgoer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
