# Generated by Django 4.1.7 on 2023-03-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
        ('ticketing', '0003_remove_order_card_number_remove_order_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgoer',
            name='balance',
            field=models.FloatField(default=0, verbose_name='User Balance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='venue_management.seattype', verbose_name='Seat Type'),
        ),
    ]
