# Generated by Django 4.1.7 on 2023-02-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_concert_remove_eventgoer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgoer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
