# Generated by Django 4.1.7 on 2023-02-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_alter_eventgoer_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concert',
        ),
    ]
