# Generated by Django 4.1.7 on 2023-02-27 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticketing', '0007_delete_concert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgoer',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='is_reseller',
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='eventgoers', related_query_name='eventgoer', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='eventgoers', related_query_name='eventgoer', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
