# Generated by Django 4.1.7 on 2023-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_alter_eventgoer_options_remove_eventgoer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('concert_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventgoer',
            options={'verbose_name': 'Eventgoer', 'verbose_name_plural': 'Eventgoers'},
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='eventgoer',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='is_reseller',
            field=models.BooleanField(default=True, verbose_name='Reseller Account'),
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='email',
            field=models.EmailField(default='', max_length=40, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
