# Generated by Django 4.1.7 on 2023-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_concert_alter_eventgoer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgoer',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='is_active',
            field=models.BooleanField(verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='is_reseller',
            field=models.BooleanField(verbose_name='Reseller Account'),
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
