# Generated by Django 4.1.7 on 2023-03-01 22:45
""""
This migration file adds two new boolean fields, is_staff and is_superuser, to the VenueManager model.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_alter_eventgoer_managers_alter_eventgoer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgoer',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AddField(
            model_name='eventgoer',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
    ]
