# Generated by Django 4.1.7 on 2023-03-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_eventgoer_is_staff_eventgoer_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventgoer',
            managers=[
            ],
        ),
    ]
