# Generated by Django 4.1.7 on 2023-03-02 06:46
"""
This migration file adds two new boolean fields, is_staff and is_superuser, to the VenueManager model.
"""
from django.db import migrations
import ticketing.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_alter_eventgoer_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventgoer',
            managers=[
                ('objects', ticketing.manager.UserManager()),
            ],
        ),
    ]
