# Generated by Django 4.1.7 on 2023-03-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_alter_eventgoer_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concert',
        ),
    ]
