# Generated by Django 4.1.7 on 2023-03-05 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0015_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../venue_management/static/venue_images'),
        ),
        migrations.AddField(
            model_name='concert',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
