# Generated by Django 4.1.7 on 2023-03-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0016_concert_concert_price_concert_concert_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='concert_price',
            new_name='ticket_price',
        ),
    ]
