# Generated by Django 4.1.7 on 2023-03-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_rename_concert_price_concert_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='concert_time',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='image',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='website',
        ),
    ]
