# Generated by Django 4.1.7 on 2023-03-06 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattype',
            name='price',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100000)], verbose_name='Ticket Price'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='price',
            field=models.FloatField(default=0, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='concerts',
            field=models.ManyToManyField(related_name='venues', to='venue_management.concert', verbose_name='Concerts'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='managers',
            field=models.ManyToManyField(related_name='venues', to='venue_management.venuemanager', verbose_name='Managers'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seat_types',
            field=models.ManyToManyField(related_name='venues', to='venue_management.seattype', verbose_name='Seat Types'),
        ),
    ]
