# Generated by Django 4.1.7 on 2023-03-07 01:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('concert_name', models.CharField(default='', max_length=60)),
                ('artist_name', models.CharField(max_length=100)),
                ('concert_date', models.DateTimeField()),
                ('venue_name', models.CharField(max_length=60, verbose_name='Name')),
                ('seat_type', models.CharField(max_length=60, verbose_name='Seat Type')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=1000000)], verbose_name='Number of Seats')),
                ('card_number', models.CharField(max_length=16, verbose_name='Credit Card Number')),
                ('cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('exp_month', models.CharField(max_length=2, verbose_name='Exipration month')),
                ('exp_year', models.CharField(max_length=4, verbose_name='Exipration year')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Card Holder Name')),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100000)], verbose_name='Price')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue_management.location', verbose_name='Location')),
            ],
        ),
    ]
