# Generated by Django 4.1.7 on 2023-03-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue_management.location', verbose_name='Location'),
        ),
    ]
