# Generated by Django 4.1.7 on 2023-02-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0002_alter_venuemanager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemanager',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
