# Generated by Django 4.1.7 on 2023-03-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
