# Generated by Django 4.1.7 on 2023-03-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0002_alter_venue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
