# Generated by Django 4.1.7 on 2023-03-02 06:13
"""
This migration file adds two new boolean fields, is_staff and is_superuser, to the VenueManager model.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0003_alter_venuemanager_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemanager',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AddField(
            model_name='venuemanager',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
    ]
