# Generated by Django 4.1.7 on 2023-03-02 06:46
"""This migration file adds two new boolean fields, is_staff and is_superuser, to the VenueManager model."""
from django.db import migrations
import venue_management.manager


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0004_venuemanager_is_staff_venuemanager_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='venuemanager',
            managers=[
                ('objects', venue_management.manager.UserManager()),
            ],
        ),
    ]
