# Generated by Django 4.1.7 on 2023-03-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0006_concert_promocode'),
        ('venue_management', '0006_promocode'),
    ]

    operations = [
    ]
